# Generated by Django 5.2.8 on 2025-12-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10),
        ),
    ]
